# NB Couldnt get the environment to install
# Weird because I used the same conda.yml file that I used in Lesson2 Exercise4
# I ran it outside of MLFlow in the end
name: eda
channels:
  - conda-forge
  - defaults
dependencies:
#  - jupyterlab=3.0.12
  - python=3.8
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.6.2   # Was 2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.13.3    # Was 0.10.21
