name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.0.1   # Was 1.14.1. Installed 2.0.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.3    # Was 0.10.31. Installed v0.13.3 to overcome protobuf errors
